/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;
import FinalProject.ConnectionClass;
import FinalProject.ConnectionClass;
import FinalProject.ConnectionClass;
import static FinalProject.ConnectionClass.con;
import FinalProject.NEUHomePage;
import FinalProject.SnellAdminLoginPage;
import FinalProject.StudentHomePage;
import FinalProject.StudentLoginPage;
import FinalProject.StudentLoginPage;
import FinalProject.StudentOrdersPage;
import FinalProject.StudentProfilePage;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Veenadharini
 */
public class MyOrdersPage extends javax.swing.JFrame {

    /**
     * Creates new form MyOrdersPage
     */
    Connection con;
    public MyOrdersPage() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameField = new javax.swing.JTextField();
        userField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        bttnCancel1 = new javax.swing.JButton();
        qrButton = new javax.swing.JButton();
        orderField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navigate = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "User ID", "Sub Total", "Taxes", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 1130, 290));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(133, 0, 0), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        jScrollPane2.setViewportView(txtReceipt);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 470, 570));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 550, 950));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        bttnCancel1.setBackground(new java.awt.Color(133, 0, 0));
        bttnCancel1.setForeground(new java.awt.Color(255, 255, 255));
        bttnCancel1.setText("Cancel Order");
        bttnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancel1ActionPerformed(evt);
            }
        });

        qrButton.setBackground(new java.awt.Color(133, 0, 0));
        qrButton.setForeground(new java.awt.Color(255, 255, 255));
        qrButton.setText("SCAN QR TO PICK-UP ORDER");
        qrButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addComponent(qrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(bttnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qrButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 1370, 100));
        jPanel1.add(orderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 72, 0, 10));

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1790, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1920, 950));

        jPanel2.setBackground(new java.awt.Color(133, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MY ORDERS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 5, 400, 120));

        navigate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navigate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account", "Back To Home Page", "My Profile", "Order Page", "Logout" }));
        navigate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigateMouseClicked(evt);
            }
        });
        navigate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigateActionPerformed(evt);
            }
        });
        jPanel2.add(navigate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 40, 160, 40));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        
        //String vendor = "Popeye";
        String user = StudentLoginPage.usernameField.getText();
        try{
            con = ConnectionClass.getConnection();
            String sql = "Select * FROM orders WHERE username = '"+user+"'";
            
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs =pst.executeQuery();

            DefaultTableModel tbl1 = (DefaultTableModel) tblOrders.getModel();
            tbl1.setRowCount(0);

            while(rs.next()){
                Object o1[] = {rs.getString("Order_ID"), rs.getString("username"),rs.getString("SubTotal"),rs.getString("Taxes"),rs.getString("Total"),rs.getString("Status"),};
                tbl1.addRow(o1);
           
            }
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        int selectedRowIndex = tblOrders.getSelectedRow();

//        if (selectedRowIndex<0){
//
//            JOptionPane.showMessageDialog(this, "Please select an order to update");
//            return;
//        }

        DefaultTableModel model = (DefaultTableModel)tblOrders.getModel();
        if (selectedRowIndex<0){

            JOptionPane.showMessageDialog(this, "Please select an order");
            return;
       }
         orderField.setText((String)tblOrders.getValueAt(selectedRowIndex, 0));
        userField.setText((String)tblOrders.getValueAt(selectedRowIndex, 1));
        String orderid = (String) tblOrders.getValueAt(selectedRowIndex, 0);
        String user = StudentLoginPage.usernameField.getText();
        try{
            
            con = ConnectionClass.getConnection();
            String sql = "Select receipt from orders WHERE Order_ID='"+orderid+"' and username = '"+user+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs =pst.executeQuery();
            //pst.execute();
            //init();
            //JOptionPane.showMessageDialog(null,"The Order has been Cancelled successfully");
            while(rs.next()){
                txtReceipt.setText(rs.getString(1));
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        
    }    
        
        
        
       
                                     


//        txt_OrderID.setText((String)tblOrders.getValueAt(selectedRowIndex, 0));
//        txt_Total.setText((String)tblOrders.getValueAt(selectedRowIndex, 4));
//        //txt_Status.setText((String)tblOrders.getValueAt(selectedRowIndex, 5));
//        comboStatus.setSelectedItem(tblOrders.getValueAt(selectedRowIndex, 5));
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void bttnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancel1ActionPerformed
       int selectedRowIndex = tblOrders.getSelectedRow();
        String orderid = (String) tblOrders.getValueAt(selectedRowIndex, 0);
        String ogstatus = (String) tblOrders.getValueAt(selectedRowIndex, 5);
        //String total = txt_Total.getText();
        String status = "Order Cancelled";
        String user = StudentLoginPage.usernameField.getText();

        
            if (ogstatus.equals( "Order Ready for Pickup")|| ogstatus.equals( "SCAN QR")|| ogstatus.equals( "Order Picked up"))
            {
               JOptionPane.showMessageDialog(null,"Unfortunately the Order cannot be cancelled now!"); 
            }
            else{
            try{
            con = ConnectionClass.getConnection();
            String sql = "Update orders SET Status='"+status+"' WHERE Order_ID='"+orderid+"' and username = '"+user+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            init();
            JOptionPane.showMessageDialog(null,"The Order has been Cancelled successfully");
                    }
        
                    
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        
                    }                                  
            }
    
    }//GEN-LAST:event_bttnCancel1ActionPerformed

    private void qrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrButtonActionPerformed
        // TODO add your handling code here:
        new StudentOrdersQRScanner().setVisible(true);
    }//GEN-LAST:event_qrButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new SnellAdminLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void navigateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_navigateMouseClicked

    private void navigateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigateActionPerformed
        // TODO add your handling code here:
        if(navigate.getSelectedItem().toString().equals("Back To Home Page")){
            String role = "";
            try{                       
                    String slotSql = ("Select role from student_info where username = '"+StudentLoginPage.usernameField.getText()+"' ");           
                    PreparedStatement slotPreparedStatement = con.prepareStatement(slotSql); 
                    ResultSet c = slotPreparedStatement.executeQuery();                       
                    while(c.next())
                    {
                     role = c.getString("role");
                    }
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
                
                if (role.equals("student")){
                    new StudentHomePage().setVisible(true);
                    dispose();
                }
                
                if (role.equals("faculty")){
                    new FacultyHomePage().setVisible(true);
                    dispose();
                }               
            
        }
        if(navigate.getSelectedItem().toString().equals("My Profile")){
            new StudentProfilePage().setVisible(true);
            dispose();
        }
        if(navigate.getSelectedItem().toString().equals("Order Page")){
            new StudentOrdersPage().setVisible(true);
            dispose();
        }
        if(navigate.getSelectedItem().toString().equals("Logout")){
            new NEUHomePage().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_navigateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new StudentProfilePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyOrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyOrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyOrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyOrdersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyOrdersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> navigate;
    public static javax.swing.JTextField orderField;
    private javax.swing.JButton qrButton;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextArea txtReceipt;
    public static javax.swing.JTextField userField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
