/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;

/**
 *
 * @author maher
 */
public class NEUHomePage extends javax.swing.JFrame {

    /**
     * Creates new form NEUHomePage
     */
    public NEUHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        StudentLogin = new javax.swing.JButton();
        FacultyLogin = new javax.swing.JButton();
        SnellAdminLogin = new javax.swing.JButton();
        SystemAdminLogin = new javax.swing.JButton();
        RestaurantManagerLogin = new javax.swing.JButton();
        CurryAdminLogin = new javax.swing.JButton();
        PopeyeSales = new javax.swing.JButton();
        CurryPromotions = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        StudentLogin.setBackground(new java.awt.Color(103, 0, 0));
        StudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StudentLogin.setForeground(new java.awt.Color(255, 255, 255));
        StudentLogin.setText("Student");
        StudentLogin.setBorder(null);
        StudentLogin.setMaximumSize(new java.awt.Dimension(160, 50));
        StudentLogin.setMinimumSize(new java.awt.Dimension(160, 50));
        StudentLogin.setPreferredSize(new java.awt.Dimension(160, 50));
        StudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentLoginActionPerformed(evt);
            }
        });

        FacultyLogin.setBackground(new java.awt.Color(103, 0, 0));
        FacultyLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FacultyLogin.setForeground(new java.awt.Color(255, 255, 255));
        FacultyLogin.setText("Faculty");
        FacultyLogin.setBorder(null);
        FacultyLogin.setMaximumSize(new java.awt.Dimension(160, 50));
        FacultyLogin.setMinimumSize(new java.awt.Dimension(160, 50));
        FacultyLogin.setPreferredSize(new java.awt.Dimension(160, 50));
        FacultyLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyLoginActionPerformed(evt);
            }
        });

        SnellAdminLogin.setBackground(new java.awt.Color(103, 0, 0));
        SnellAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SnellAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        SnellAdminLogin.setText("Snell Admin");
        SnellAdminLogin.setBorder(null);
        SnellAdminLogin.setMaximumSize(new java.awt.Dimension(160, 50));
        SnellAdminLogin.setMinimumSize(new java.awt.Dimension(160, 50));
        SnellAdminLogin.setPreferredSize(new java.awt.Dimension(160, 50));
        SnellAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnellAdminLoginActionPerformed(evt);
            }
        });

        SystemAdminLogin.setBackground(new java.awt.Color(103, 0, 0));
        SystemAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SystemAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        SystemAdminLogin.setText("System Admin");
        SystemAdminLogin.setBorder(null);
        SystemAdminLogin.setMaximumSize(new java.awt.Dimension(160, 50));
        SystemAdminLogin.setMinimumSize(new java.awt.Dimension(160, 50));
        SystemAdminLogin.setPreferredSize(new java.awt.Dimension(160, 50));
        SystemAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemAdminLoginActionPerformed(evt);
            }
        });

        RestaurantManagerLogin.setBackground(new java.awt.Color(103, 0, 0));
        RestaurantManagerLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RestaurantManagerLogin.setForeground(new java.awt.Color(255, 255, 255));
        RestaurantManagerLogin.setText("Restaurant Manager");
        RestaurantManagerLogin.setBorder(null);
        RestaurantManagerLogin.setMaximumSize(new java.awt.Dimension(160, 50));
        RestaurantManagerLogin.setMinimumSize(new java.awt.Dimension(160, 50));
        RestaurantManagerLogin.setPreferredSize(new java.awt.Dimension(160, 50));
        RestaurantManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaurantManagerLoginActionPerformed(evt);
            }
        });

        CurryAdminLogin.setBackground(new java.awt.Color(103, 0, 0));
        CurryAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CurryAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        CurryAdminLogin.setText("Curry Center");
        CurryAdminLogin.setBorder(null);
        CurryAdminLogin.setMaximumSize(new java.awt.Dimension(160, 50));
        CurryAdminLogin.setMinimumSize(new java.awt.Dimension(160, 50));
        CurryAdminLogin.setPreferredSize(new java.awt.Dimension(160, 50));
        CurryAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurryAdminLoginActionPerformed(evt);
            }
        });

        PopeyeSales.setBackground(new java.awt.Color(103, 0, 0));
        PopeyeSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PopeyeSales.setForeground(new java.awt.Color(255, 255, 255));
        PopeyeSales.setText("Popeye Sales ");
        PopeyeSales.setBorder(null);
        PopeyeSales.setMaximumSize(new java.awt.Dimension(160, 50));
        PopeyeSales.setMinimumSize(new java.awt.Dimension(160, 50));
        PopeyeSales.setPreferredSize(new java.awt.Dimension(160, 50));
        PopeyeSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopeyeSalesActionPerformed(evt);
            }
        });

        CurryPromotions.setBackground(new java.awt.Color(103, 0, 0));
        CurryPromotions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CurryPromotions.setForeground(new java.awt.Color(255, 255, 255));
        CurryPromotions.setText("Curry Promotions");
        CurryPromotions.setBorder(null);
        CurryPromotions.setMaximumSize(new java.awt.Dimension(160, 50));
        CurryPromotions.setMinimumSize(new java.awt.Dimension(160, 50));
        CurryPromotions.setPreferredSize(new java.awt.Dimension(160, 50));
        CurryPromotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurryPromotionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(StudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(FacultyLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(SnellAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(SystemAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(RestaurantManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(CurryAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(PopeyeSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(CurryPromotions, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SnellAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestaurantManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurryAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopeyeSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurryPromotions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1920, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design (5).gif"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FacultyLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyLoginActionPerformed
        // TODO add your handling code here:
        new StudentLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_FacultyLoginActionPerformed

    private void StudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentLoginActionPerformed
        // TODO add your handling code here:
        new StudentLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_StudentLoginActionPerformed

    private void SnellAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnellAdminLoginActionPerformed
        // TODO add your handling code here:
         new SnellAdminLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_SnellAdminLoginActionPerformed

    private void SystemAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemAdminLoginActionPerformed
        // TODO add your handling code here:
         new adminLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_SystemAdminLoginActionPerformed

    private void RestaurantManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaurantManagerLoginActionPerformed
        // TODO add your handling code here:
        new RestaurantManagerLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_RestaurantManagerLoginActionPerformed

    private void CurryAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurryAdminLoginActionPerformed
        // TODO add your handling code here:
        new CurryAdminLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_CurryAdminLoginActionPerformed

    private void PopeyeSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopeyeSalesActionPerformed
        // TODO add your handling code here:
        new PopeyeSalesLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_PopeyeSalesActionPerformed

    private void CurryPromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurryPromotionsActionPerformed
        // TODO add your handling code here:
        new CurryMarketingLoginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_CurryPromotionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEUHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEUHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEUHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEUHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEUHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CurryAdminLogin;
    private javax.swing.JButton CurryPromotions;
    private javax.swing.JButton FacultyLogin;
    private javax.swing.JButton PopeyeSales;
    private javax.swing.JButton RestaurantManagerLogin;
    private javax.swing.JButton SnellAdminLogin;
    private javax.swing.JButton StudentLogin;
    private javax.swing.JButton SystemAdminLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
