/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;
import FinalProject.ConnectionClass;
import FinalProject.ConnectionClass;
import FinalProject.ConnectionClass;
import FinalProject.ConnectionClass;
import FinalProject.NEUHomePage;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author Veenadharini
 */
public class PopeyeManagerPage extends javax.swing.JFrame {

    /**
     * Creates new form PopeyeManagerPage
     */
    Connection con;
    public PopeyeManagerPage() {
        initComponents();
        
        init();
        //lbl_ScanMsg.setVisible(false);
        //txtOffer.setVisible(false);
        //txtOffer.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void init() {
        
        String vendor = "Popeye";
        try{
            con = ConnectionClass.getConnection();
            String sql = "Select * FROM orders WHERE Vender_ID = '"+vendor+"'";
            
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs =pst.executeQuery();

            DefaultTableModel tbl1 = (DefaultTableModel) tblOrders.getModel();
            tbl1.setRowCount(0);

            while(rs.next()){
                Object o1[] = {rs.getString("Order_ID"), rs.getString("username"),rs.getString("SubTotal"),rs.getString("Taxes"),rs.getString("Total"),rs.getString("Status"),};
                tbl1.addRow(o1);
           
            }
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_OrderID = new javax.swing.JTextField();
        txt_Total = new javax.swing.JTextField();
        comboStatus = new javax.swing.JComboBox<>();
        bttnUpdate = new javax.swing.JButton();
        bttnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1920, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/popoyes.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 0, 360, 100));

        jButton13.setText("Logout");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 100));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setText("Order_ID:");

        jLabel3.setText("Total:");

        jLabel4.setText("Status:");

        txt_OrderID.setEditable(false);

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Statuses..", "Order Placed, Awaiting Confirmation", "Order Accepted, in Preparation", "Order Ready for Pickup", "SCAN QR", "Order Delayed", "Order Picked up" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        bttnUpdate.setText("Update Order");
        bttnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUpdateActionPerformed(evt);
            }
        });

        bttnCancel.setText("Cancel Order");
        bttnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_OrderID)
                            .addComponent(txt_Total)
                            .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(bttnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_OrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(468, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, 700, 980));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "User ID", "Sub Total", "Taxes", "Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 1130, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUpdateActionPerformed
        
        String orderid = txt_OrderID.getText();
        String total = txt_Total.getText();
        String status = comboStatus.getSelectedItem().toString();
        
        try{
            con = ConnectionClass.getConnection();
            String sql = "Update orders SET Total='"+total+"',Status='"+status+"' WHERE Order_ID='"+orderid+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            init();
            JOptionPane.showMessageDialog(null,"The Order has been updated successfully");
            //txt_OrderID.setText("");
            //txt_Total.setText("");
            //comboStatus.setSelectedIndex(0);
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        String combo = comboStatus.getSelectedItem().toString();
         
        if (combo.equals("SCAN QR")) {
            
              try{
    String QrCodeData= txt_OrderID.getText();
    String filePath= "C:\\Users\\hamza\\OneDrive\\Desktop\\qr\\Qr.png";
    String charset= "UTF-8";
    Map <EncodeHintType,ErrorCorrectionLevel> hintMap= new HashMap <EncodeHintType,ErrorCorrectionLevel> ();
    hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
    BitMatrix  matrix= new MultiFormatWriter().encode(
    new String (QrCodeData.getBytes(charset),charset),
    BarcodeFormat.QR_CODE,200,200,hintMap);
    
    MatrixToImageWriter.writeToFile(matrix, filePath.substring(filePath.lastIndexOf('.')+1),new File(filePath));
        System.out.println("Qr code has been generated at the location "+filePath);
        
           JFrame frame = new JFrame();
        ImageIcon icon = new ImageIcon("C:\\Users\\hamza\\OneDrive\\Desktop\\qr\\Qr.png");
        JLabel label = new JLabel(icon);
        frame.add(label);
  
  frame.pack();
  
  frame.setVisible(true);  
frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }
    catch(Exception e){
        System.out.println(e);
    
    }
    //lbl_ScanMsg.setVisible(true);
    //lbl_ScanMsg.setText("Please SCAN the QR to pick up the Order");
;        
        }
        else if (combo.equals("Order Picked up")) {
        
        }
        
        
     
    }//GEN-LAST:event_bttnUpdateActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        if("Order Placed, Awaiting Confirmation".equals(comboStatus)){
          //txt_Status.setText("Order Placed, Awaiting Confirmation");
        }
          else if("Order Accepted, in Preparation".equals(comboStatus.getSelectedItem())){
                  //txt_Status.setText("Order Accepted, in Preparation");
                  }
          else if("Order Ready for Pickup".equals(comboStatus.getSelectedItem())){
                  //txt_Status.setText("Order Ready for Pickup");
                  }
          else if("Order Delayed".equals(comboStatus.getSelectedItem())){
                 // txt_Status.setText("Order Delayed");
                  }
          else if("Order Picked up".equals(comboStatus.getSelectedItem())){
                  //txt_Status.setText("Order Picked up");
                  }
        
    }//GEN-LAST:event_comboStatusActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        int selectedRowIndex = tblOrders.getSelectedRow();
        
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select an order to update");
            return;            
        }
        
        DefaultTableModel model = (DefaultTableModel)tblOrders.getModel();
        
        txt_OrderID.setText((String)tblOrders.getValueAt(selectedRowIndex, 0));
        txt_Total.setText((String)tblOrders.getValueAt(selectedRowIndex, 4));
        //txt_Status.setText((String)tblOrders.getValueAt(selectedRowIndex, 5));
        comboStatus.setSelectedItem(tblOrders.getValueAt(selectedRowIndex, 5));
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void bttnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelActionPerformed
        String orderid = txt_OrderID.getText();
        String total = txt_Total.getText();
        String status = "Order Cancelled";
        
        try{
            con = ConnectionClass.getConnection();
            String sql = "Update orders SET Total='"+total+"',Status='"+status+"' WHERE Order_ID='"+orderid+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            init();
            JOptionPane.showMessageDialog(null,"The Order has been Cancelled successfully");
            txt_OrderID.setText("");
            txt_Total.setText("");
            comboStatus.setSelectedIndex(0);
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_bttnCancelActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        new NEUHomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopeyeManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopeyeManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopeyeManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopeyeManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopeyeManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancel;
    private javax.swing.JButton bttnUpdate;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txt_OrderID;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables

    
}
