/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;

/**
 *
 * @author maher
 */
public class SnellLibraryBookingFloor2 extends javax.swing.JFrame {

    /**
     * Creates new form SnellLibraryBookingFloor2
     */
    public SnellLibraryBookingFloor2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        T8 = new javax.swing.JLabel();
        T20S1 = new javax.swing.JToggleButton();
        T6 = new javax.swing.JLabel();
        T9 = new javax.swing.JLabel();
        T10 = new javax.swing.JLabel();
        T22S1 = new javax.swing.JToggleButton();
        T23S1 = new javax.swing.JToggleButton();
        T21S1 = new javax.swing.JToggleButton();
        T24 = new javax.swing.JLabel();
        T25 = new javax.swing.JLabel();
        T24S1 = new javax.swing.JToggleButton();
        T25S1 = new javax.swing.JToggleButton();
        T26 = new javax.swing.JLabel();
        T27 = new javax.swing.JLabel();
        T28 = new javax.swing.JLabel();
        T29 = new javax.swing.JLabel();
        T30 = new javax.swing.JLabel();
        T31 = new javax.swing.JLabel();
        T32 = new javax.swing.JLabel();
        T26S1 = new javax.swing.JToggleButton();
        T26S2 = new javax.swing.JToggleButton();
        T26S3 = new javax.swing.JToggleButton();
        T27S1 = new javax.swing.JToggleButton();
        T26S4 = new javax.swing.JToggleButton();
        T27S2 = new javax.swing.JToggleButton();
        T28S1 = new javax.swing.JToggleButton();
        T28S2 = new javax.swing.JToggleButton();
        T32S1 = new javax.swing.JToggleButton();
        T32S2 = new javax.swing.JToggleButton();
        T31S4 = new javax.swing.JToggleButton();
        T31S1 = new javax.swing.JToggleButton();
        T31S2 = new javax.swing.JToggleButton();
        T31S3 = new javax.swing.JToggleButton();
        T30S1 = new javax.swing.JToggleButton();
        T30S2 = new javax.swing.JToggleButton();
        T29S1 = new javax.swing.JToggleButton();
        T29S2 = new javax.swing.JToggleButton();
        T29S3 = new javax.swing.JToggleButton();
        T29S4 = new javax.swing.JToggleButton();
        Circle1 = new javax.swing.JToggleButton();
        Circle2 = new javax.swing.JToggleButton();
        DMC1 = new javax.swing.JToggleButton();
        DMC2 = new javax.swing.JToggleButton();
        DMC3 = new javax.swing.JToggleButton();
        DMC4 = new javax.swing.JToggleButton();
        DMC5 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        seatNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        T8.setForeground(new java.awt.Color(255, 255, 255));
        T8.setText("T23");
        jPanel1.add(T8);
        T8.setBounds(300, 460, 30, 16);

        buttonGroup1.add(T20S1);
        T20S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T20S1.setForeground(new java.awt.Color(51, 51, 51));
        T20S1.setText("T20S1");
        T20S1.setBorder(null);
        T20S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T20S1StateChanged(evt);
            }
        });
        T20S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T20S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T20S1);
        T20S1.setBounds(680, 400, 40, 40);

        T6.setForeground(new java.awt.Color(255, 255, 255));
        T6.setText("T20");
        jPanel1.add(T6);
        T6.setBounds(670, 460, 30, 16);

        T9.setForeground(new java.awt.Color(255, 255, 255));
        T9.setText("T21");
        jPanel1.add(T9);
        T9.setBounds(550, 460, 30, 16);

        T10.setForeground(new java.awt.Color(255, 255, 255));
        T10.setText("T22");
        jPanel1.add(T10);
        T10.setBounds(430, 460, 30, 16);

        buttonGroup1.add(T22S1);
        T22S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T22S1.setForeground(new java.awt.Color(51, 51, 51));
        T22S1.setText("T22S1");
        T22S1.setBorder(null);
        T22S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T22S1StateChanged(evt);
            }
        });
        T22S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T22S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T22S1);
        T22S1.setBounds(440, 400, 40, 40);

        buttonGroup1.add(T23S1);
        T23S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T23S1.setForeground(new java.awt.Color(51, 51, 51));
        T23S1.setText("T23S1");
        T23S1.setBorder(null);
        T23S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T23S1StateChanged(evt);
            }
        });
        T23S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T23S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T23S1);
        T23S1.setBounds(320, 400, 40, 40);

        buttonGroup1.add(T21S1);
        T21S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T21S1.setForeground(new java.awt.Color(51, 51, 51));
        T21S1.setText("T21S1");
        T21S1.setBorder(null);
        T21S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T21S1StateChanged(evt);
            }
        });
        T21S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T21S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T21S1);
        T21S1.setBounds(560, 400, 40, 40);

        T24.setForeground(new java.awt.Color(255, 255, 255));
        T24.setText("T24");
        jPanel1.add(T24);
        T24.setBounds(140, 330, 30, 16);

        T25.setForeground(new java.awt.Color(255, 255, 255));
        T25.setText("T25");
        jPanel1.add(T25);
        T25.setBounds(60, 270, 30, 16);

        buttonGroup1.add(T24S1);
        T24S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T24S1.setForeground(new java.awt.Color(51, 51, 51));
        T24S1.setText("T24S1");
        T24S1.setBorder(null);
        T24S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T24S1StateChanged(evt);
            }
        });
        T24S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T24S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T24S1);
        T24S1.setBounds(190, 320, 40, 40);

        buttonGroup1.add(T25S1);
        T25S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T25S1.setForeground(new java.awt.Color(51, 51, 51));
        T25S1.setText("T25S1");
        T25S1.setBorder(null);
        T25S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T25S1StateChanged(evt);
            }
        });
        T25S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T25S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T25S1);
        T25S1.setBounds(110, 260, 40, 40);

        T26.setForeground(new java.awt.Color(255, 255, 255));
        T26.setText("T26");
        jPanel1.add(T26);
        T26.setBounds(390, 880, 30, 16);

        T27.setForeground(new java.awt.Color(255, 255, 255));
        T27.setText("T27");
        jPanel1.add(T27);
        T27.setBounds(650, 870, 30, 16);

        T28.setForeground(new java.awt.Color(255, 255, 255));
        T28.setText("T28");
        jPanel1.add(T28);
        T28.setBounds(650, 640, 30, 16);

        T29.setForeground(new java.awt.Color(255, 255, 255));
        T29.setText("T29");
        jPanel1.add(T29);
        T29.setBounds(1220, 610, 30, 16);

        T30.setForeground(new java.awt.Color(255, 255, 255));
        T30.setText("T32");
        jPanel1.add(T30);
        T30.setBounds(0, 980, 30, 16);

        T31.setForeground(new java.awt.Color(255, 255, 255));
        T31.setText("T30");
        jPanel1.add(T31);
        T31.setBounds(1330, 450, 30, 16);

        T32.setForeground(new java.awt.Color(255, 255, 255));
        T32.setText("T31");
        jPanel1.add(T32);
        T32.setBounds(1620, 420, 30, 16);

        buttonGroup1.add(T26S1);
        T26S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T26S1.setForeground(new java.awt.Color(51, 51, 51));
        T26S1.setText("T26S1");
        T26S1.setBorder(null);
        T26S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T26S1StateChanged(evt);
            }
        });
        T26S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T26S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T26S1);
        T26S1.setBounds(420, 810, 40, 40);

        buttonGroup1.add(T26S2);
        T26S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T26S2.setForeground(new java.awt.Color(51, 51, 51));
        T26S2.setText("T26S2");
        T26S2.setBorder(null);
        T26S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T26S2StateChanged(evt);
            }
        });
        T26S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T26S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T26S2);
        T26S2.setBounds(420, 910, 40, 40);

        buttonGroup1.add(T26S3);
        T26S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T26S3.setForeground(new java.awt.Color(51, 51, 51));
        T26S3.setText("T26S3");
        T26S3.setBorder(null);
        T26S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T26S3StateChanged(evt);
            }
        });
        T26S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T26S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T26S3);
        T26S3.setBounds(340, 910, 40, 40);

        buttonGroup1.add(T27S1);
        T27S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T27S1.setForeground(new java.awt.Color(51, 51, 51));
        T27S1.setText("T27S1");
        T27S1.setBorder(null);
        T27S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T27S1StateChanged(evt);
            }
        });
        T27S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T27S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T27S1);
        T27S1.setBounds(570, 860, 40, 40);

        buttonGroup1.add(T26S4);
        T26S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T26S4.setForeground(new java.awt.Color(51, 51, 51));
        T26S4.setText("T26S4");
        T26S4.setBorder(null);
        T26S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T26S4StateChanged(evt);
            }
        });
        T26S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T26S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T26S4);
        T26S4.setBounds(340, 810, 40, 40);

        buttonGroup1.add(T27S2);
        T27S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T27S2.setForeground(new java.awt.Color(51, 51, 51));
        T27S2.setText("T27S2");
        T27S2.setBorder(null);
        T27S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T27S2StateChanged(evt);
            }
        });
        T27S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T27S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T27S2);
        T27S2.setBounds(710, 860, 40, 40);

        buttonGroup1.add(T28S1);
        T28S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T28S1.setForeground(new java.awt.Color(51, 51, 51));
        T28S1.setText("T28S1");
        T28S1.setBorder(null);
        T28S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T28S1StateChanged(evt);
            }
        });
        T28S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T28S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T28S1);
        T28S1.setBounds(570, 630, 40, 40);

        buttonGroup1.add(T28S2);
        T28S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T28S2.setForeground(new java.awt.Color(51, 51, 51));
        T28S2.setText("T28S2");
        T28S2.setBorder(null);
        T28S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T28S2StateChanged(evt);
            }
        });
        T28S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T28S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T28S2);
        T28S2.setBounds(710, 630, 40, 40);

        buttonGroup1.add(T32S1);
        T32S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T32S1.setForeground(new java.awt.Color(51, 51, 51));
        T32S1.setText("T32S1");
        T32S1.setBorder(null);
        T32S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T32S1StateChanged(evt);
            }
        });
        T32S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T32S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T32S1);
        T32S1.setBounds(60, 930, 40, 40);

        buttonGroup1.add(T32S2);
        T32S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T32S2.setForeground(new java.awt.Color(51, 51, 51));
        T32S2.setText("T32S2");
        T32S2.setBorder(null);
        T32S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T32S2StateChanged(evt);
            }
        });
        T32S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T32S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T32S2);
        T32S2.setBounds(60, 1000, 40, 40);

        buttonGroup1.add(T31S4);
        T31S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T31S4.setForeground(new java.awt.Color(51, 51, 51));
        T31S4.setText("T31S4");
        T31S4.setBorder(null);
        T31S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T31S4StateChanged(evt);
            }
        });
        T31S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T31S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T31S4);
        T31S4.setBounds(1560, 450, 40, 40);

        buttonGroup1.add(T31S1);
        T31S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T31S1.setForeground(new java.awt.Color(51, 51, 51));
        T31S1.setText("T31S1");
        T31S1.setBorder(null);
        T31S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T31S1StateChanged(evt);
            }
        });
        T31S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T31S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T31S1);
        T31S1.setBounds(1650, 450, 40, 40);

        buttonGroup1.add(T31S2);
        T31S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T31S2.setForeground(new java.awt.Color(51, 51, 51));
        T31S2.setText("T31S2");
        T31S2.setBorder(null);
        T31S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T31S2StateChanged(evt);
            }
        });
        T31S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T31S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T31S2);
        T31S2.setBounds(1650, 360, 40, 40);

        buttonGroup1.add(T31S3);
        T31S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T31S3.setForeground(new java.awt.Color(51, 51, 51));
        T31S3.setText("T26S3");
        T31S3.setBorder(null);
        T31S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T31S3StateChanged(evt);
            }
        });
        T31S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T31S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T31S3);
        T31S3.setBounds(1560, 360, 40, 40);

        buttonGroup1.add(T30S1);
        T30S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T30S1.setForeground(new java.awt.Color(51, 51, 51));
        T30S1.setText("T30S1");
        T30S1.setBorder(null);
        T30S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T30S1StateChanged(evt);
            }
        });
        T30S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T30S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T30S1);
        T30S1.setBounds(1380, 370, 40, 40);

        buttonGroup1.add(T30S2);
        T30S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T30S2.setForeground(new java.awt.Color(51, 51, 51));
        T30S2.setText("T30S1");
        T30S2.setBorder(null);
        T30S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T30S2StateChanged(evt);
            }
        });
        T30S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T30S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T30S2);
        T30S2.setBounds(1270, 370, 40, 40);

        buttonGroup1.add(T29S1);
        T29S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T29S1.setForeground(new java.awt.Color(51, 51, 51));
        T29S1.setText("T29S1");
        T29S1.setBorder(null);
        T29S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T29S1StateChanged(evt);
            }
        });
        T29S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T29S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T29S1);
        T29S1.setBounds(1120, 550, 40, 40);

        buttonGroup1.add(T29S2);
        T29S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T29S2.setForeground(new java.awt.Color(51, 51, 51));
        T29S2.setText("T29S2");
        T29S2.setBorder(null);
        T29S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T29S2StateChanged(evt);
            }
        });
        T29S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T29S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T29S2);
        T29S2.setBounds(1120, 650, 40, 40);

        buttonGroup1.add(T29S3);
        T29S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T29S3.setForeground(new java.awt.Color(51, 51, 51));
        T29S3.setText("T29S3");
        T29S3.setBorder(null);
        T29S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T29S3StateChanged(evt);
            }
        });
        T29S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T29S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T29S3);
        T29S3.setBounds(1290, 650, 40, 40);

        buttonGroup1.add(T29S4);
        T29S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T29S4.setForeground(new java.awt.Color(51, 51, 51));
        T29S4.setText("T29S4");
        T29S4.setBorder(null);
        T29S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T29S4StateChanged(evt);
            }
        });
        T29S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T29S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T29S4);
        T29S4.setBounds(1290, 550, 40, 40);

        Circle1.setBackground(new java.awt.Color(137, 2, 2));
        buttonGroup1.add(Circle1);
        Circle1.setText("Circle1");
        Circle1.setBorder(null);
        jPanel1.add(Circle1);
        Circle1.setBounds(370, 630, 50, 50);

        Circle2.setBackground(new java.awt.Color(137, 2, 2));
        buttonGroup1.add(Circle2);
        Circle2.setText("Circle2");
        Circle2.setBorder(null);
        jPanel1.add(Circle2);
        Circle2.setBounds(1510, 590, 50, 60);

        DMC1.setBackground(new java.awt.Color(83, 82, 134));
        buttonGroup1.add(DMC1);
        DMC1.setForeground(new java.awt.Color(255, 255, 255));
        DMC1.setText("DMC1");
        DMC1.setBorder(null);
        DMC1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DMC1StateChanged(evt);
            }
        });
        DMC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMC1ActionPerformed(evt);
            }
        });
        jPanel1.add(DMC1);
        DMC1.setBounds(260, 220, 110, 110);

        DMC2.setBackground(new java.awt.Color(83, 82, 134));
        buttonGroup1.add(DMC2);
        DMC2.setForeground(new java.awt.Color(255, 255, 255));
        DMC2.setText("DMC2");
        DMC2.setBorder(null);
        DMC2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DMC2StateChanged(evt);
            }
        });
        DMC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMC2ActionPerformed(evt);
            }
        });
        jPanel1.add(DMC2);
        DMC2.setBounds(380, 220, 120, 110);

        DMC3.setBackground(new java.awt.Color(83, 82, 134));
        buttonGroup1.add(DMC3);
        DMC3.setForeground(new java.awt.Color(255, 255, 255));
        DMC3.setText("DMC3");
        DMC3.setBorder(null);
        DMC3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DMC3StateChanged(evt);
            }
        });
        DMC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMC3ActionPerformed(evt);
            }
        });
        jPanel1.add(DMC3);
        DMC3.setBounds(510, 220, 120, 110);

        DMC4.setBackground(new java.awt.Color(83, 82, 134));
        buttonGroup1.add(DMC4);
        DMC4.setForeground(new java.awt.Color(255, 255, 255));
        DMC4.setText("DMC4");
        DMC4.setBorder(null);
        DMC4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DMC4StateChanged(evt);
            }
        });
        DMC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMC4ActionPerformed(evt);
            }
        });
        jPanel1.add(DMC4);
        DMC4.setBounds(640, 220, 110, 110);

        DMC5.setBackground(new java.awt.Color(83, 82, 134));
        buttonGroup1.add(DMC5);
        DMC5.setForeground(new java.awt.Color(255, 255, 255));
        DMC5.setText("DMC5");
        DMC5.setBorder(null);
        DMC5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DMC5StateChanged(evt);
            }
        });
        DMC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DMC5ActionPerformed(evt);
            }
        });
        jPanel1.add(DMC5);
        DMC5.setBounds(1360, 190, 60, 70);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 160, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame 4 (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        seatNumber.setText("jTextField1");
        jPanel1.add(seatNumber);
        seatNumber.setBounds(410, 760, 71, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T20S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T20S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T20S1StateChanged

    private void T20S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T20S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T20S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T20S1ActionPerformed

    private void T22S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T22S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T22S1StateChanged

    private void T22S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T22S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T22S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T22S1ActionPerformed

    private void T23S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T23S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T23S1StateChanged

    private void T23S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T23S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T23S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T23S1ActionPerformed

    private void T21S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T21S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T21S1StateChanged

    private void T21S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T21S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T21S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T21S1ActionPerformed

    private void T24S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T24S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T24S1StateChanged

    private void T24S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T24S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T24S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T24S1ActionPerformed

    private void T25S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T25S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T25S1StateChanged

    private void T25S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T25S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T25S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T25S1ActionPerformed

    private void T26S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T26S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T26S1StateChanged

    private void T26S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T26S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T26S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T26S1ActionPerformed

    private void T26S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T26S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T26S2StateChanged

    private void T26S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T26S2ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T26S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T26S2ActionPerformed

    private void T26S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T26S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T26S3StateChanged

    private void T26S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T26S3ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T26S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T26S3ActionPerformed

    private void T27S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T27S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T27S1StateChanged

    private void T27S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T27S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T27S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T27S1ActionPerformed

    private void T26S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T26S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T26S4StateChanged

    private void T26S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T26S4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T26S4ActionPerformed

    private void T27S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T27S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T27S2StateChanged

    private void T27S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T27S2ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T27S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T27S2ActionPerformed

    private void T28S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T28S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T28S1StateChanged

    private void T28S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T28S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T28S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T28S1ActionPerformed

    private void T28S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T28S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T28S2StateChanged

    private void T28S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T28S2ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T28S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T28S2ActionPerformed

    private void T32S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T32S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T32S1StateChanged

    private void T32S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T32S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T32S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T32S1ActionPerformed

    private void T32S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T32S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T32S2StateChanged

    private void T32S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T32S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T32S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T32S2ActionPerformed

    private void T31S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T31S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T31S4StateChanged

    private void T31S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T31S4ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T31S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T31S4ActionPerformed

    private void T31S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T31S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T31S1StateChanged

    private void T31S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T31S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T31S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T31S1ActionPerformed

    private void T31S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T31S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T31S2StateChanged

    private void T31S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T31S2ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T31S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T31S2ActionPerformed

    private void T31S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T31S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T31S3StateChanged

    private void T31S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T31S3ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T31S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T31S3ActionPerformed

    private void T30S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T30S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T30S1StateChanged

    private void T30S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T30S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T30S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T30S1ActionPerformed

    private void T30S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T30S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T30S2StateChanged

    private void T30S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T30S2ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T30S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T30S2ActionPerformed

    private void T29S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T29S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T29S1StateChanged

    private void T29S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T29S1ActionPerformed
        // TODO add your handling code here:
         seatNumber.setText(T29S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T29S1ActionPerformed

    private void T29S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T29S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T29S2StateChanged

    private void T29S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T29S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T29S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T29S2ActionPerformed

    private void T29S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T29S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T29S3StateChanged

    private void T29S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T29S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T29S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T29S3ActionPerformed

    private void T29S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T29S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T29S4StateChanged

    private void T29S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T29S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T29S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T29S4ActionPerformed

    private void DMC1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DMC1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DMC1StateChanged

    private void DMC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMC1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(DMC1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_DMC1ActionPerformed

    private void DMC2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DMC2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DMC2StateChanged

    private void DMC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMC2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(DMC2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_DMC2ActionPerformed

    private void DMC3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DMC3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DMC3StateChanged

    private void DMC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMC3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(DMC3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_DMC3ActionPerformed

    private void DMC4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DMC4StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_DMC4StateChanged

    private void DMC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMC4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(DMC1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_DMC4ActionPerformed

    private void DMC5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DMC5StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_DMC5StateChanged

    private void DMC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DMC5ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(DMC5.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_DMC5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           new SnellLibraryFloorPicker().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnellLibraryBookingFloor2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Circle1;
    private javax.swing.JToggleButton Circle2;
    private javax.swing.JToggleButton DMC1;
    private javax.swing.JToggleButton DMC2;
    private javax.swing.JToggleButton DMC3;
    private javax.swing.JToggleButton DMC4;
    private javax.swing.JToggleButton DMC5;
    private javax.swing.JLabel T10;
    private javax.swing.JToggleButton T20S1;
    private javax.swing.JToggleButton T21S1;
    private javax.swing.JToggleButton T22S1;
    private javax.swing.JToggleButton T23S1;
    private javax.swing.JLabel T24;
    private javax.swing.JToggleButton T24S1;
    private javax.swing.JLabel T25;
    private javax.swing.JToggleButton T25S1;
    private javax.swing.JLabel T26;
    private javax.swing.JToggleButton T26S1;
    private javax.swing.JToggleButton T26S2;
    private javax.swing.JToggleButton T26S3;
    private javax.swing.JToggleButton T26S4;
    private javax.swing.JLabel T27;
    private javax.swing.JToggleButton T27S1;
    private javax.swing.JToggleButton T27S2;
    private javax.swing.JLabel T28;
    private javax.swing.JToggleButton T28S1;
    private javax.swing.JToggleButton T28S2;
    private javax.swing.JLabel T29;
    private javax.swing.JToggleButton T29S1;
    private javax.swing.JToggleButton T29S2;
    private javax.swing.JToggleButton T29S3;
    private javax.swing.JToggleButton T29S4;
    private javax.swing.JLabel T30;
    private javax.swing.JToggleButton T30S1;
    private javax.swing.JToggleButton T30S2;
    private javax.swing.JLabel T31;
    private javax.swing.JToggleButton T31S1;
    private javax.swing.JToggleButton T31S2;
    private javax.swing.JToggleButton T31S3;
    private javax.swing.JToggleButton T31S4;
    private javax.swing.JLabel T32;
    private javax.swing.JToggleButton T32S1;
    private javax.swing.JToggleButton T32S2;
    private javax.swing.JLabel T6;
    private javax.swing.JLabel T8;
    private javax.swing.JLabel T9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField seatNumber;
    // End of variables declaration//GEN-END:variables
}
