/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;

/**
 *
 * @author maher
 */
public class SnellLibraryBookingFloor3 extends javax.swing.JFrame {

    /**
     * Creates new form SnellLibraryBookingFloor2
     */
    public SnellLibraryBookingFloor3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        T33 = new javax.swing.JLabel();
        T34 = new javax.swing.JLabel();
        T35 = new javax.swing.JLabel();
        T36 = new javax.swing.JLabel();
        T37 = new javax.swing.JLabel();
        T38 = new javax.swing.JLabel();
        T39 = new javax.swing.JLabel();
        T40 = new javax.swing.JLabel();
        T41 = new javax.swing.JLabel();
        T42 = new javax.swing.JLabel();
        T43 = new javax.swing.JLabel();
        T44 = new javax.swing.JLabel();
        T45 = new javax.swing.JLabel();
        T46 = new javax.swing.JLabel();
        T47 = new javax.swing.JLabel();
        T51 = new javax.swing.JLabel();
        T33S1 = new javax.swing.JToggleButton();
        T33S2 = new javax.swing.JToggleButton();
        T33S3 = new javax.swing.JToggleButton();
        T33S4 = new javax.swing.JToggleButton();
        T34S1 = new javax.swing.JToggleButton();
        T34S2 = new javax.swing.JToggleButton();
        T34S3 = new javax.swing.JToggleButton();
        T34S4 = new javax.swing.JToggleButton();
        T38S1 = new javax.swing.JToggleButton();
        T39S1 = new javax.swing.JToggleButton();
        T40S1 = new javax.swing.JToggleButton();
        T41S1 = new javax.swing.JToggleButton();
        T37S2 = new javax.swing.JToggleButton();
        T37S1 = new javax.swing.JToggleButton();
        T36S2 = new javax.swing.JToggleButton();
        T36S1 = new javax.swing.JToggleButton();
        T35S2 = new javax.swing.JToggleButton();
        T42S1 = new javax.swing.JToggleButton();
        T42S2 = new javax.swing.JToggleButton();
        T46S1 = new javax.swing.JToggleButton();
        T46S2 = new javax.swing.JToggleButton();
        T46S3 = new javax.swing.JToggleButton();
        T46S4 = new javax.swing.JToggleButton();
        T45S1 = new javax.swing.JToggleButton();
        T45S2 = new javax.swing.JToggleButton();
        T45S3 = new javax.swing.JToggleButton();
        T45S4 = new javax.swing.JToggleButton();
        T44S1 = new javax.swing.JToggleButton();
        T44S2 = new javax.swing.JToggleButton();
        T44S3 = new javax.swing.JToggleButton();
        T44S4 = new javax.swing.JToggleButton();
        T43S1 = new javax.swing.JToggleButton();
        T43S2 = new javax.swing.JToggleButton();
        T47S1 = new javax.swing.JToggleButton();
        T47S2 = new javax.swing.JToggleButton();
        T48S1 = new javax.swing.JToggleButton();
        T48S2 = new javax.swing.JToggleButton();
        T48S3 = new javax.swing.JToggleButton();
        T48S4 = new javax.swing.JToggleButton();
        T35S1 = new javax.swing.JToggleButton();
        R352 = new javax.swing.JToggleButton();
        R353 = new javax.swing.JToggleButton();
        R354 = new javax.swing.JToggleButton();
        R355 = new javax.swing.JToggleButton();
        R351 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        seatNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        T33.setForeground(new java.awt.Color(255, 255, 255));
        T33.setText("T33");
        jPanel1.add(T33);
        T33.setBounds(670, 650, 30, 16);

        T34.setForeground(new java.awt.Color(255, 255, 255));
        T34.setText("T34");
        jPanel1.add(T34);
        T34.setBounds(680, 470, 30, 16);

        T35.setForeground(new java.awt.Color(255, 255, 255));
        T35.setText("T35");
        jPanel1.add(T35);
        T35.setBounds(680, 290, 30, 16);

        T36.setForeground(new java.awt.Color(255, 255, 255));
        T36.setText("T36");
        jPanel1.add(T36);
        T36.setBounds(320, 490, 30, 16);

        T37.setForeground(new java.awt.Color(255, 255, 255));
        T37.setText("T37");
        jPanel1.add(T37);
        T37.setBounds(320, 290, 30, 16);

        T38.setForeground(new java.awt.Color(255, 255, 255));
        T38.setText("T38");
        jPanel1.add(T38);
        T38.setBounds(40, 720, 30, 16);

        T39.setForeground(new java.awt.Color(255, 255, 255));
        T39.setText("T39");
        jPanel1.add(T39);
        T39.setBounds(40, 630, 30, 16);

        T40.setForeground(new java.awt.Color(255, 255, 255));
        T40.setText("T40");
        jPanel1.add(T40);
        T40.setBounds(40, 520, 30, 16);

        T41.setForeground(new java.awt.Color(255, 255, 255));
        T41.setText("T41");
        jPanel1.add(T41);
        T41.setBounds(40, 420, 30, 16);

        T42.setForeground(new java.awt.Color(255, 255, 255));
        T42.setText("T42");
        jPanel1.add(T42);
        T42.setBounds(1100, 570, 30, 16);

        T43.setForeground(new java.awt.Color(255, 255, 255));
        T43.setText("T43");
        jPanel1.add(T43);
        T43.setBounds(1110, 450, 30, 16);

        T44.setForeground(new java.awt.Color(255, 255, 255));
        T44.setText("T44");
        jPanel1.add(T44);
        T44.setBounds(1240, 280, 30, 16);

        T45.setForeground(new java.awt.Color(255, 255, 255));
        T45.setText("T45");
        jPanel1.add(T45);
        T45.setBounds(1080, 90, 30, 16);

        T46.setForeground(new java.awt.Color(255, 255, 255));
        T46.setText("T46");
        jPanel1.add(T46);
        T46.setBounds(1400, 510, 30, 16);

        T47.setForeground(new java.awt.Color(255, 255, 255));
        T47.setText("T47");
        jPanel1.add(T47);
        T47.setBounds(1340, 780, 30, 16);

        T51.setForeground(new java.awt.Color(255, 255, 255));
        T51.setText("T48");
        jPanel1.add(T51);
        T51.setBounds(1650, 970, 30, 16);

        T33S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T33S1.setForeground(new java.awt.Color(51, 51, 51));
        T33S1.setText("T33S1");
        T33S1.setBorder(null);
        T33S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T33S1StateChanged(evt);
            }
        });
        T33S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T33S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T33S1);
        T33S1.setBounds(710, 580, 40, 40);

        T33S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T33S2.setForeground(new java.awt.Color(51, 51, 51));
        T33S2.setText("T33S2");
        T33S2.setBorder(null);
        T33S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T33S2StateChanged(evt);
            }
        });
        T33S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T33S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T33S2);
        T33S2.setBounds(630, 580, 40, 40);

        T33S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T33S3.setForeground(new java.awt.Color(51, 51, 51));
        T33S3.setText("T33S3");
        T33S3.setBorder(null);
        T33S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T33S3StateChanged(evt);
            }
        });
        T33S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T33S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T33S3);
        T33S3.setBounds(630, 690, 40, 40);

        T33S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T33S4.setForeground(new java.awt.Color(51, 51, 51));
        T33S4.setText("T33S4");
        T33S4.setBorder(null);
        T33S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T33S4StateChanged(evt);
            }
        });
        T33S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T33S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T33S4);
        T33S4.setBounds(710, 690, 40, 40);

        T34S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T34S1.setForeground(new java.awt.Color(51, 51, 51));
        T34S1.setText("T34S1");
        T34S1.setBorder(null);
        T34S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T34S1StateChanged(evt);
            }
        });
        T34S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T34S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T34S1);
        T34S1.setBounds(710, 410, 40, 40);

        T34S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T34S2.setForeground(new java.awt.Color(51, 51, 51));
        T34S2.setText("T34S2");
        T34S2.setBorder(null);
        T34S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T34S2StateChanged(evt);
            }
        });
        T34S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T34S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T34S2);
        T34S2.setBounds(630, 410, 40, 40);

        T34S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T34S3.setForeground(new java.awt.Color(51, 51, 51));
        T34S3.setText("T34S3");
        T34S3.setBorder(null);
        T34S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T34S3StateChanged(evt);
            }
        });
        T34S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T34S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T34S3);
        T34S3.setBounds(630, 510, 40, 40);

        T34S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T34S4.setForeground(new java.awt.Color(51, 51, 51));
        T34S4.setText("T34S4");
        T34S4.setBorder(null);
        T34S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T34S4StateChanged(evt);
            }
        });
        T34S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T34S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T34S4);
        T34S4.setBounds(710, 510, 40, 40);

        T38S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T38S1.setForeground(new java.awt.Color(51, 51, 51));
        T38S1.setText("T38S1");
        T38S1.setBorder(null);
        T38S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T38S1StateChanged(evt);
            }
        });
        T38S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T38S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T38S1);
        T38S1.setBounds(110, 710, 40, 40);

        T39S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T39S1.setForeground(new java.awt.Color(51, 51, 51));
        T39S1.setText("T39S1");
        T39S1.setBorder(null);
        T39S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T39S1StateChanged(evt);
            }
        });
        T39S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T39S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T39S1);
        T39S1.setBounds(110, 620, 40, 40);

        T40S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T40S1.setForeground(new java.awt.Color(51, 51, 51));
        T40S1.setText("T40S1");
        T40S1.setBorder(null);
        T40S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T40S1StateChanged(evt);
            }
        });
        T40S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T40S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T40S1);
        T40S1.setBounds(110, 510, 40, 40);

        T41S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T41S1.setForeground(new java.awt.Color(51, 51, 51));
        T41S1.setText("T41S1");
        T41S1.setBorder(null);
        T41S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T41S1StateChanged(evt);
            }
        });
        T41S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T41S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T41S1);
        T41S1.setBounds(110, 410, 40, 40);

        T37S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T37S2.setForeground(new java.awt.Color(51, 51, 51));
        T37S2.setText("T37S2");
        T37S2.setBorder(null);
        T37S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T37S2StateChanged(evt);
            }
        });
        T37S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T37S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T37S2);
        T37S2.setBounds(280, 230, 40, 40);

        T37S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T37S1.setForeground(new java.awt.Color(51, 51, 51));
        T37S1.setText("T37S1");
        T37S1.setBorder(null);
        T37S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T37S1StateChanged(evt);
            }
        });
        T37S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T37S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T37S1);
        T37S1.setBounds(360, 230, 40, 40);

        T36S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T36S2.setForeground(new java.awt.Color(51, 51, 51));
        T36S2.setText("T36S2");
        T36S2.setBorder(null);
        T36S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T36S2StateChanged(evt);
            }
        });
        T36S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T36S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T36S2);
        T36S2.setBounds(280, 420, 40, 40);

        T36S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T36S1.setForeground(new java.awt.Color(51, 51, 51));
        T36S1.setText("T36S1");
        T36S1.setBorder(null);
        T36S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T36S1StateChanged(evt);
            }
        });
        T36S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T36S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T36S1);
        T36S1.setBounds(360, 420, 40, 40);

        T35S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T35S2.setForeground(new java.awt.Color(51, 51, 51));
        T35S2.setText("T35S2");
        T35S2.setBorder(null);
        T35S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T35S2StateChanged(evt);
            }
        });
        T35S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T35S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T35S2);
        T35S2.setBounds(630, 230, 40, 40);

        T42S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T42S1.setForeground(new java.awt.Color(51, 51, 51));
        T42S1.setText("T42S1");
        T42S1.setBorder(null);
        T42S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T42S1StateChanged(evt);
            }
        });
        T42S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T42S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T42S1);
        T42S1.setBounds(1040, 560, 40, 40);

        T42S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T42S2.setForeground(new java.awt.Color(51, 51, 51));
        T42S2.setText("T42S2");
        T42S2.setBorder(null);
        T42S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T42S2StateChanged(evt);
            }
        });
        T42S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T42S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T42S2);
        T42S2.setBounds(1160, 560, 40, 40);

        T46S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T46S1.setForeground(new java.awt.Color(51, 51, 51));
        T46S1.setText("T46S1");
        T46S1.setBorder(null);
        T46S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T46S1StateChanged(evt);
            }
        });
        T46S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T46S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T46S1);
        T46S1.setBounds(1330, 450, 40, 40);

        T46S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T46S2.setForeground(new java.awt.Color(51, 51, 51));
        T46S2.setText("T46S2");
        T46S2.setBorder(null);
        T46S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T46S2StateChanged(evt);
            }
        });
        T46S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T46S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T46S2);
        T46S2.setBounds(1330, 520, 40, 40);

        T46S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T46S3.setForeground(new java.awt.Color(51, 51, 51));
        T46S3.setText("T46S3");
        T46S3.setBorder(null);
        T46S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T46S3StateChanged(evt);
            }
        });
        T46S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T46S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T46S3);
        T46S3.setBounds(1450, 520, 40, 40);

        T46S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T46S4.setForeground(new java.awt.Color(51, 51, 51));
        T46S4.setText("T46S4");
        T46S4.setBorder(null);
        T46S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T46S4StateChanged(evt);
            }
        });
        T46S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T46S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T46S4);
        T46S4.setBounds(1450, 450, 40, 40);

        T45S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T45S1.setForeground(new java.awt.Color(51, 51, 51));
        T45S1.setText("T45S1");
        T45S1.setBorder(null);
        T45S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T45S1StateChanged(evt);
            }
        });
        T45S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T45S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T45S1);
        T45S1.setBounds(1130, 20, 40, 40);

        T45S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T45S2.setForeground(new java.awt.Color(51, 51, 51));
        T45S2.setText("T45S2");
        T45S2.setBorder(null);
        T45S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T45S2StateChanged(evt);
            }
        });
        T45S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T45S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T45S2);
        T45S2.setBounds(1050, 20, 40, 40);

        T45S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T45S3.setForeground(new java.awt.Color(51, 51, 51));
        T45S3.setText("T45S3");
        T45S3.setBorder(null);
        T45S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T45S3StateChanged(evt);
            }
        });
        T45S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T45S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T45S3);
        T45S3.setBounds(1130, 130, 40, 40);

        T45S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T45S4.setForeground(new java.awt.Color(51, 51, 51));
        T45S4.setText("T45S4");
        T45S4.setBorder(null);
        T45S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T45S4StateChanged(evt);
            }
        });
        T45S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T45S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T45S4);
        T45S4.setBounds(1050, 130, 40, 40);

        T44S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T44S1.setForeground(new java.awt.Color(51, 51, 51));
        T44S1.setText("T44S1");
        T44S1.setBorder(null);
        T44S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T44S1StateChanged(evt);
            }
        });
        T44S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T44S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T44S1);
        T44S1.setBounds(1270, 210, 40, 40);

        T44S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T44S2.setForeground(new java.awt.Color(51, 51, 51));
        T44S2.setText("T44S2");
        T44S2.setBorder(null);
        T44S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T44S2StateChanged(evt);
            }
        });
        T44S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T44S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T44S2);
        T44S2.setBounds(1190, 210, 40, 40);

        T44S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T44S3.setForeground(new java.awt.Color(51, 51, 51));
        T44S3.setText("T44S3");
        T44S3.setBorder(null);
        T44S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T44S3StateChanged(evt);
            }
        });
        T44S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T44S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T44S3);
        T44S3.setBounds(1190, 320, 40, 40);

        T44S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T44S4.setForeground(new java.awt.Color(51, 51, 51));
        T44S4.setText("T44S4");
        T44S4.setBorder(null);
        T44S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T44S4StateChanged(evt);
            }
        });
        T44S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T44S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T44S4);
        T44S4.setBounds(1270, 320, 40, 40);

        T43S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T43S1.setForeground(new java.awt.Color(51, 51, 51));
        T43S1.setText("T43S1");
        T43S1.setBorder(null);
        T43S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T43S1StateChanged(evt);
            }
        });
        T43S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T43S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T43S1);
        T43S1.setBounds(1040, 440, 40, 40);

        T43S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T43S2.setForeground(new java.awt.Color(51, 51, 51));
        T43S2.setText("T43S2");
        T43S2.setBorder(null);
        T43S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T43S2StateChanged(evt);
            }
        });
        T43S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T43S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T43S2);
        T43S2.setBounds(1160, 440, 40, 40);

        T47S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T47S1.setForeground(new java.awt.Color(51, 51, 51));
        T47S1.setText("T47S1");
        T47S1.setBorder(null);
        T47S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T47S1StateChanged(evt);
            }
        });
        T47S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T47S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T47S1);
        T47S1.setBounds(1270, 760, 40, 40);

        T47S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T47S2.setForeground(new java.awt.Color(51, 51, 51));
        T47S2.setText("T47S2");
        T47S2.setBorder(null);
        T47S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T47S2StateChanged(evt);
            }
        });
        T47S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T47S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T47S2);
        T47S2.setBounds(1390, 760, 40, 40);

        T48S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T48S1.setForeground(new java.awt.Color(51, 51, 51));
        T48S1.setText("T48S1");
        T48S1.setBorder(null);
        T48S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T48S1StateChanged(evt);
            }
        });
        T48S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T48S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T48S1);
        T48S1.setBounds(1600, 900, 40, 40);

        T48S2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T48S2.setForeground(new java.awt.Color(51, 51, 51));
        T48S2.setText("T48S2");
        T48S2.setBorder(null);
        T48S2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T48S2StateChanged(evt);
            }
        });
        T48S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T48S2ActionPerformed(evt);
            }
        });
        jPanel1.add(T48S2);
        T48S2.setBounds(1680, 900, 40, 40);

        T48S3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T48S3.setForeground(new java.awt.Color(51, 51, 51));
        T48S3.setText("T48S3");
        T48S3.setBorder(null);
        T48S3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T48S3StateChanged(evt);
            }
        });
        T48S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T48S3ActionPerformed(evt);
            }
        });
        jPanel1.add(T48S3);
        T48S3.setBounds(1680, 1000, 40, 40);

        T48S4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T48S4.setForeground(new java.awt.Color(51, 51, 51));
        T48S4.setText("T48S4");
        T48S4.setBorder(null);
        T48S4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T48S4StateChanged(evt);
            }
        });
        T48S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T48S4ActionPerformed(evt);
            }
        });
        jPanel1.add(T48S4);
        T48S4.setBounds(1600, 1000, 40, 40);

        T35S1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        T35S1.setForeground(new java.awt.Color(51, 51, 51));
        T35S1.setText("T35S1");
        T35S1.setBorder(null);
        T35S1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                T35S1StateChanged(evt);
            }
        });
        T35S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T35S1ActionPerformed(evt);
            }
        });
        jPanel1.add(T35S1);
        T35S1.setBounds(710, 230, 40, 40);

        R352.setBackground(new java.awt.Color(83, 82, 134));
        R352.setForeground(new java.awt.Color(255, 255, 255));
        R352.setText("352");
        R352.setBorder(null);
        R352.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R352StateChanged(evt);
            }
        });
        R352.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R352ActionPerformed(evt);
            }
        });
        jPanel1.add(R352);
        R352.setBounds(1500, 200, 90, 200);

        R353.setBackground(new java.awt.Color(83, 82, 134));
        R353.setForeground(new java.awt.Color(255, 255, 255));
        R353.setText("353");
        R353.setBorder(null);
        R353.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R353StateChanged(evt);
            }
        });
        R353.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R353ActionPerformed(evt);
            }
        });
        jPanel1.add(R353);
        R353.setBounds(1610, 420, 100, 200);

        R354.setBackground(new java.awt.Color(83, 82, 134));
        R354.setForeground(new java.awt.Color(255, 255, 255));
        R354.setText("354");
        R354.setBorder(null);
        R354.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R354StateChanged(evt);
            }
        });
        R354.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R354ActionPerformed(evt);
            }
        });
        jPanel1.add(R354);
        R354.setBounds(1720, 640, 90, 180);

        R355.setBackground(new java.awt.Color(83, 82, 134));
        R355.setForeground(new java.awt.Color(255, 255, 255));
        R355.setText("355");
        R355.setBorder(null);
        R355.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R355StateChanged(evt);
            }
        });
        R355.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R355ActionPerformed(evt);
            }
        });
        jPanel1.add(R355);
        R355.setBounds(1820, 850, 90, 190);

        R351.setBackground(new java.awt.Color(83, 82, 134));
        R351.setForeground(new java.awt.Color(255, 255, 255));
        R351.setText("351");
        R351.setBorder(null);
        R351.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                R351StateChanged(evt);
            }
        });
        R351.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R351ActionPerformed(evt);
            }
        });
        jPanel1.add(R351);
        R351.setBounds(1410, 10, 90, 170);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 150, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame 3 (4).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        seatNumber.setText("jTextField1");
        jPanel1.add(seatNumber);
        seatNumber.setBounds(410, 760, 71, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T33S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T33S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T33S1StateChanged

    private void T33S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T33S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T33S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_T33S1ActionPerformed

    private void T33S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T33S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T33S2StateChanged

    private void T33S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T33S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T33S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T33S2ActionPerformed

    private void T33S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T33S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T33S3StateChanged

    private void T33S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T33S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T33S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T33S3ActionPerformed

    private void T33S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T33S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T33S4StateChanged

    private void T33S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T33S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T33S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T33S4ActionPerformed

    private void T34S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T34S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T34S1StateChanged

    private void T34S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T34S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T34S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T34S1ActionPerformed

    private void T34S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T34S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T34S2StateChanged

    private void T34S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T34S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T34S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T34S2ActionPerformed

    private void T34S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T34S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T34S3StateChanged

    private void T34S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T34S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T34S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T34S3ActionPerformed

    private void T34S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T34S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T34S4StateChanged

    private void T34S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T34S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T34S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T34S4ActionPerformed

    private void T35S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T35S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T35S1StateChanged

    private void T35S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T35S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T35S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T35S1ActionPerformed

    private void T35S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T35S2StateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_T35S2StateChanged

    private void T35S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T35S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T35S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T35S2ActionPerformed

    private void T36S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T36S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T36S1StateChanged

    private void T36S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T36S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T36S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T36S1ActionPerformed

    private void T36S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T36S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T36S2StateChanged

    private void T36S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T36S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T36S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T36S2ActionPerformed

    private void T37S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T37S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T37S1StateChanged

    private void T37S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T37S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T37S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T37S1ActionPerformed

    private void T37S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T37S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T37S2StateChanged

    private void T37S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T37S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T37S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T37S2ActionPerformed

    private void T38S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T38S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T38S1StateChanged

    private void T38S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T38S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T38S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T38S1ActionPerformed

    private void T39S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T39S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T39S1StateChanged

    private void T39S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T39S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T39S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T39S1ActionPerformed

    private void T40S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T40S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T40S1StateChanged

    private void T40S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T40S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T40S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T40S1ActionPerformed

    private void T41S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T41S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T41S1StateChanged

    private void T41S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T41S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T41S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T41S1ActionPerformed

    private void T42S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T42S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T42S1StateChanged

    private void T42S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T42S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T42S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T42S1ActionPerformed

    private void T42S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T42S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T42S2StateChanged

    private void T42S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T42S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T42S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T42S2ActionPerformed

    private void T43S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T43S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T43S1StateChanged

    private void T43S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T43S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T43S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T43S1ActionPerformed

    private void T43S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T43S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T43S2StateChanged

    private void T43S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T43S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T43S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T43S2ActionPerformed

    private void T44S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T44S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T44S1StateChanged

    private void T44S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T44S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T44S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T44S1ActionPerformed

    private void T44S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T44S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T44S2StateChanged

    private void T44S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T44S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T44S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T44S2ActionPerformed

    private void T44S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T44S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T44S3StateChanged

    private void T44S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T44S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T44S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T44S3ActionPerformed

    private void T44S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T44S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T44S4StateChanged

    private void T44S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T44S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T44S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T44S4ActionPerformed

    private void T45S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T45S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T45S1StateChanged

    private void T45S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T45S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T45S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T45S1ActionPerformed

    private void T45S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T45S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T45S2StateChanged

    private void T45S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T45S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T45S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T45S2ActionPerformed

    private void T45S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T45S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T45S3StateChanged

    private void T45S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T45S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T45S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T45S3ActionPerformed

    private void T45S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T45S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T45S4StateChanged

    private void T45S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T45S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T45S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T45S4ActionPerformed

    private void T46S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T46S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T46S1StateChanged

    private void T46S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T46S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T45S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T46S1ActionPerformed

    private void T46S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T46S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T46S2StateChanged

    private void T46S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T46S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T46S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T46S2ActionPerformed

    private void T46S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T46S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T46S3StateChanged

    private void T46S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T46S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T46S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T46S3ActionPerformed

    private void T46S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T46S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T46S4StateChanged

    private void T46S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T46S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T46S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T46S4ActionPerformed

    private void T48S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T48S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T48S1StateChanged

    private void T48S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T48S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T48S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T48S1ActionPerformed

    private void T48S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T48S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T48S2StateChanged

    private void T48S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T48S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T48S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T48S2ActionPerformed

    private void T48S3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T48S3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T48S3StateChanged

    private void T48S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T48S3ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T48S3.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T48S3ActionPerformed

    private void T48S4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T48S4StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T48S4StateChanged

    private void T48S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T48S4ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T48S4.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T48S4ActionPerformed

    private void T47S1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T47S1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T47S1StateChanged

    private void T47S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T47S1ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T47S1.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T47S1ActionPerformed

    private void T47S2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_T47S2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_T47S2StateChanged

    private void T47S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T47S2ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(T47S2.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_T47S2ActionPerformed

    private void R351StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R351StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_R351StateChanged

    private void R351ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R351ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(R351.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_R351ActionPerformed

    private void R352StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R352StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_R352StateChanged

    private void R352ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R352ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(R352.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_R352ActionPerformed

    private void R353StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R353StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_R353StateChanged

    private void R353ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R353ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(R353.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_R353ActionPerformed

    private void R354StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R354StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_R354StateChanged

    private void R354ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R354ActionPerformed
        // TODO add your handling code here:
        
        seatNumber.setText(R354.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_R354ActionPerformed

    private void R355StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_R355StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_R355StateChanged

    private void R355ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R355ActionPerformed
        // TODO add your handling code here:
        seatNumber.setText(R355.getText());
        new SnellLibrarySlotBooking().setVisible(true);
        dispose();
    }//GEN-LAST:event_R355ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          new SnellLibraryFloorPicker().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnellLibraryBookingFloor3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnellLibraryBookingFloor3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton R351;
    private javax.swing.JToggleButton R352;
    private javax.swing.JToggleButton R353;
    private javax.swing.JToggleButton R354;
    private javax.swing.JToggleButton R355;
    private javax.swing.JLabel T33;
    private javax.swing.JToggleButton T33S1;
    private javax.swing.JToggleButton T33S2;
    private javax.swing.JToggleButton T33S3;
    private javax.swing.JToggleButton T33S4;
    private javax.swing.JLabel T34;
    private javax.swing.JToggleButton T34S1;
    private javax.swing.JToggleButton T34S2;
    private javax.swing.JToggleButton T34S3;
    private javax.swing.JToggleButton T34S4;
    private javax.swing.JLabel T35;
    private javax.swing.JToggleButton T35S1;
    private javax.swing.JToggleButton T35S2;
    private javax.swing.JLabel T36;
    private javax.swing.JToggleButton T36S1;
    private javax.swing.JToggleButton T36S2;
    private javax.swing.JLabel T37;
    private javax.swing.JToggleButton T37S1;
    private javax.swing.JToggleButton T37S2;
    private javax.swing.JLabel T38;
    private javax.swing.JToggleButton T38S1;
    private javax.swing.JLabel T39;
    private javax.swing.JToggleButton T39S1;
    private javax.swing.JLabel T40;
    private javax.swing.JToggleButton T40S1;
    private javax.swing.JLabel T41;
    private javax.swing.JToggleButton T41S1;
    private javax.swing.JLabel T42;
    private javax.swing.JToggleButton T42S1;
    private javax.swing.JToggleButton T42S2;
    private javax.swing.JLabel T43;
    private javax.swing.JToggleButton T43S1;
    private javax.swing.JToggleButton T43S2;
    private javax.swing.JLabel T44;
    private javax.swing.JToggleButton T44S1;
    private javax.swing.JToggleButton T44S2;
    private javax.swing.JToggleButton T44S3;
    private javax.swing.JToggleButton T44S4;
    private javax.swing.JLabel T45;
    private javax.swing.JToggleButton T45S1;
    private javax.swing.JToggleButton T45S2;
    private javax.swing.JToggleButton T45S3;
    private javax.swing.JToggleButton T45S4;
    private javax.swing.JLabel T46;
    private javax.swing.JToggleButton T46S1;
    private javax.swing.JToggleButton T46S2;
    private javax.swing.JToggleButton T46S3;
    private javax.swing.JToggleButton T46S4;
    private javax.swing.JLabel T47;
    private javax.swing.JToggleButton T47S1;
    private javax.swing.JToggleButton T47S2;
    private javax.swing.JToggleButton T48S1;
    private javax.swing.JToggleButton T48S2;
    private javax.swing.JToggleButton T48S3;
    private javax.swing.JToggleButton T48S4;
    private javax.swing.JLabel T51;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField seatNumber;
    // End of variables declaration//GEN-END:variables
}
