/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinalProject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author maher
 */
public class StudentHomePage extends javax.swing.JFrame {

    /**
     * Creates new form StudentHomePage
     */
    Connection con;
    public StudentHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        curryFoodOrder = new javax.swing.JButton();
        myProfile = new javax.swing.JButton();
        snellLibraryBooking = new javax.swing.JButton();
        navigate = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        curryFoodOrder.setBackground(new java.awt.Color(133, 0, 0));
        curryFoodOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        curryFoodOrder.setForeground(new java.awt.Color(255, 255, 255));
        curryFoodOrder.setText("Curry Food Order");
        curryFoodOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curryFoodOrderActionPerformed(evt);
            }
        });
        jPanel1.add(curryFoodOrder);
        curryFoodOrder.setBounds(790, 670, 360, 90);

        myProfile.setBackground(new java.awt.Color(133, 0, 0));
        myProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myProfile.setForeground(new java.awt.Color(255, 255, 255));
        myProfile.setText("My Profile");
        myProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileActionPerformed(evt);
            }
        });
        jPanel1.add(myProfile);
        myProfile.setBounds(790, 340, 360, 90);

        snellLibraryBooking.setBackground(new java.awt.Color(133, 0, 0));
        snellLibraryBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        snellLibraryBooking.setForeground(new java.awt.Color(255, 255, 255));
        snellLibraryBooking.setText("Snell Library Booking");
        snellLibraryBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snellLibraryBookingActionPerformed(evt);
            }
        });
        jPanel1.add(snellLibraryBooking);
        snellLibraryBooking.setBounds(790, 500, 360, 90);

        navigate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        navigate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account", "Back To Home Page", "My Profile", "Order Page", "Logout" }));
        navigate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navigateMouseClicked(evt);
            }
        });
        navigate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigateActionPerformed(evt);
            }
        });
        jPanel1.add(navigate);
        navigate.setBounds(1730, 90, 160, 40);

        jLabel2.setText("Student");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1830, 1040, 60, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Frame 2 (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void curryFoodOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curryFoodOrderActionPerformed
        // TODO add your handling code here:
        new StudentOrdersPage().setVisible(true);
        dispose();
       

    }//GEN-LAST:event_curryFoodOrderActionPerformed

    private void myProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileActionPerformed
        // TODO add your handling code here:
        new StudentProfilePage().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_myProfileActionPerformed

    private void snellLibraryBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snellLibraryBookingActionPerformed
        // TODO add your handling code here:
      
        String username = StudentLoginPage.usernameField.getText();
        String status = "suspended";
        String state = "";
         try {
        
             con = (Connection) ConnectionClass.getConnection();
            Statement StudentsStatement = (Statement) con.createStatement();
            String slotSql = ("Select status from student_info where username = '"+username+"'" );
            PreparedStatement slotsPreparedStatement = con.prepareStatement(slotSql);
            ResultSet resultSet = slotsPreparedStatement.executeQuery();
           while (resultSet.next()) { 
           state = resultSet.getString("status");
           }
          
           
          
           
          
            
            
    
    } 
           
               catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
           }
         if (status.equals(state)) {
           JOptionPane.showMessageDialog(null, "Your account is forbidden from making any bookings, contact Library Admin for further information: snellstaff@gmail.com");
           }
         else {
        new SnellLibraryDatePicker().setVisible(true);
                dispose();
         }
            
    }//GEN-LAST:event_snellLibraryBookingActionPerformed

    private void navigateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navigateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_navigateMouseClicked

    private void navigateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigateActionPerformed
        // TODO add your handling code here:
        if(navigate.getSelectedItem().toString().equals("Back To Home Page")){
            new StudentHomePage().setVisible(true);
            dispose();
        }
        if(navigate.getSelectedItem().toString().equals("My Profile")){
            new StudentProfilePage().setVisible(true);
            dispose();
        }
        if(navigate.getSelectedItem().toString().equals("Order Page")){
            new StudentOrdersPage().setVisible(true);
            dispose();
        }
        if(navigate.getSelectedItem().toString().equals("Logout")){
            new NEUHomePage().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_navigateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton curryFoodOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton myProfile;
    private javax.swing.JComboBox<String> navigate;
    private javax.swing.JButton snellLibraryBooking;
    // End of variables declaration//GEN-END:variables
}
